CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(32) NOT NULL DEFAULT 'CUSTOMER',
    provider VARCHAR(255),
    provider_id VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    domain VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE product_metadata (
    product_id BIGINT NOT NULL REFERENCES products(id),
    metadata_key VARCHAR(255) NOT NULL,
    metadata_value VARCHAR(255),
    PRIMARY KEY (product_id, metadata_key)
);

CREATE TABLE entitlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    code VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    UNIQUE (product_id, code)
);

CREATE TABLE policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    licensing_model VARCHAR(32) NOT NULL,
    max_machines INTEGER NOT NULL,
    max_seats INTEGER NOT NULL,
    validity_days INTEGER NOT NULL,
    heartbeat_interval_minutes INTEGER NOT NULL,
    heartbeat_grace_period_minutes INTEGER NOT NULL,
    offline_ttl_days INTEGER NOT NULL,
    min_version VARCHAR(255),
    max_version VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE policy_entitlements (
    policy_id BIGINT NOT NULL REFERENCES policies(id),
    entitlement_code VARCHAR(255) NOT NULL,
    PRIMARY KEY (policy_id, entitlement_code)
);

CREATE TABLE licenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_key VARCHAR(255) NOT NULL UNIQUE,
    hostname VARCHAR(255),
    application_name VARCHAR(255),
    email VARCHAR(255),
    customer_name VARCHAR(255),
    customer_email VARCHAR(255),
    expiry TIMESTAMP,
    active BOOLEAN NOT NULL,
    status VARCHAR(32) NOT NULL,
    revoked_at TIMESTAMP,
    suspended_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    user_id BIGINT REFERENCES users(id),
    organization_id BIGINT REFERENCES organizations(id),
    product_id BIGINT REFERENCES products(id),
    policy_id BIGINT REFERENCES policies(id)
);

CREATE TABLE license_custom_fields (
    license_id BIGINT NOT NULL REFERENCES licenses(id),
    field_key VARCHAR(255) NOT NULL,
    field_value VARCHAR(255),
    PRIMARY KEY (license_id, field_key)
);

CREATE TABLE machines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_id BIGINT NOT NULL REFERENCES licenses(id),
    fingerprint_hash VARCHAR(128) NOT NULL,
    fingerprint VARCHAR(512) NOT NULL,
    name VARCHAR(255),
    platform VARCHAR(255),
    version VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    last_seen_at TIMESTAMP,
    last_heartbeat_at TIMESTAMP,
    deactivated_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    UNIQUE (license_id, fingerprint_hash)
);

CREATE TABLE offline_license_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_id BIGINT NOT NULL REFERENCES licenses(id),
    machine_id BIGINT REFERENCES machines(id),
    token_hash VARCHAR(128) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE client_api_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    token_prefix VARCHAR(20) NOT NULL,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL,
    expires_at TIMESTAMP,
    product_id BIGINT REFERENCES products(id),
    license_id BIGINT REFERENCES licenses(id),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(120) NOT NULL,
    actor VARCHAR(80) NOT NULL,
    resource_type VARCHAR(80) NOT NULL,
    resource_id VARCHAR(255),
    description VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE audit_event_metadata (
    audit_event_id BIGINT NOT NULL REFERENCES audit_events(id),
    metadata_key VARCHAR(255) NOT NULL,
    metadata_value VARCHAR(255),
    PRIMARY KEY (audit_event_id, metadata_key)
);

CREATE INDEX idx_licenses_status ON licenses(status);
CREATE INDEX idx_machines_license_status ON machines(license_id, status);
CREATE INDEX idx_audit_events_created_at ON audit_events(created_at);
