CREATE TABLE billing_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    policy_id BIGINT NOT NULL REFERENCES policies(id),
    amount_cents BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    billing_interval VARCHAR(32) NOT NULL,
    trial_days INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    provider VARCHAR(32) NOT NULL,
    provider_price_id VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE billing_plan_metadata (
    billing_plan_id BIGINT NOT NULL REFERENCES billing_plans(id),
    metadata_key VARCHAR(255) NOT NULL,
    metadata_value VARCHAR(255),
    PRIMARY KEY (billing_plan_id, metadata_key)
);

CREATE TABLE billing_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    plan_id BIGINT NOT NULL REFERENCES billing_plans(id),
    status VARCHAR(32) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    provider_customer_id VARCHAR(255),
    provider_subscription_id VARCHAR(255),
    current_period_start TIMESTAMP,
    current_period_end TIMESTAMP,
    cancel_at_period_end BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_billing_subscriptions_org ON billing_subscriptions(organization_id);
CREATE INDEX idx_billing_subscriptions_status_period ON billing_subscriptions(status, current_period_end);
